'use client';

import React, { useState } from 'react';
import Link from 'next/link';

interface Article {
  title: string;
  content: React.ReactNode;
}

interface Section {
  title: string;
  articles: Article[];
}

export default function ConstitutionPage() {
  const [searchTerm, setSearchTerm] = useState('');
  const [expandedSection, setExpandedSection] = useState<number | null>(0);

  const toggleSection = (index: number) => {
    setExpandedSection(expandedSection === index ? null : index);
  };

  const sections: Section[] = [
    {
      title: 'Preamble',
      articles: [
        {
          title: 'Motto & Declaration',
          content: (
            <p>
              We, the members of OhaBuEnyi Age Grade of Okwojo Ngwo, Enugu State, Enugu, Nigeria, 
              seeking to foster unity, brotherly love, mutual welfare, and community development 
              among ourselves, do solemnly declare and enact this Constitution to govern our 
              collective operations, discipline, and support networks.
            </p>
          ),
        },
      ],
    },
    {
      title: 'Article I: General Provisions',
      articles: [
        {
          title: 'Section 1: Name',
          content: <p>The organization shall be known, called, and addressed as the <strong>OhaBuEnyi Age Grade</strong> (hereinafter referred to as the "Age Grade").</p>,
        },
        {
          title: 'Section 2: Patronage & Scope',
          content: <p>The registered office of the Age Grade shall be located within Okwojo Ngwo. Its membership extends to native sons of Okwojo Ngwo born within the constitutional cohort dates (January 1, 1998 to December 31, 2002).</p>,
        },
      ],
    },
    {
      title: 'Article II: Objectives & Motto',
      articles: [
        {
          title: 'Section 1: Motto',
          content: <p>The motto of the Age Grade shall be: <strong>"Oha Bu Enyi" (Unity is Strength)</strong>.</p>,
        },
        {
          title: 'Section 2: Core Objectives',
          content: (
            <ul className="list-disc pl-5 space-y-1.5">
              <li>To promote peace, harmony, and progress among members.</li>
              <li>To provide mutual assistance, benevolence, and physical/moral support to members in times of joy or distress.</li>
              <li>To contribute to the socioeconomic development and cultural heritage preservation of Okwojo Ngwo community.</li>
              <li>To uphold moral rectitude and promote youth empowerment.</li>
            </ul>
          ),
        },
      ],
    },
    {
      title: 'Article III: Membership & Registration',
      articles: [
        {
          title: 'Section 1: Eligibility',
          content: <p>Membership is strictly restricted to male individuals born between January 1, 1998 and December 31, 2002 who are native sons or legally integrated residents of Okwojo Ngwo community.</p>,
        },
        {
          title: 'Section 2: Registration & Verification',
          content: <p>New members must provide a valid verification code generated by the executive admin panel, fill out the registration form, and submit official proofs of identity including a profile picture and birth certificate (subject to admin validation).</p>,
        },
        {
          title: 'Section 3: Code of Conduct',
          content: <p>Every member must exhibit high levels of integrity, respect, and compliance with the regulations of the Age Grade. Factionalism, public misconduct, or insubordination to the Executive Committee will attract heavy sanctions.</p>,
        },
      ],
    },
    {
      title: 'Article IV: Financial Obligations',
      articles: [
        {
          title: 'Section 1: Dues and Levies',
          content: <p>All active members shall pay monthly dues as determined by the General Assembly. Occasional levies may be enacted in case of community development projects or special member welfare programs.</p>,
        },
        {
          title: 'Section 2: Settle Payments Flow',
          content: <p>Dues must be paid into the official Age Grade bank account. Upon transfer, members must submit a verification request via the portal with payment confirmations. System balances are only updated upon Admin verification.</p>,
        },
        {
          title: 'Section 3: Overdue Accounts',
          content: <p>Unpaid dues shall aggregate as outstanding debt. Overdue balances for more than 6 months without reasonable cause will attract secondary penalties or restrictions on welfare claims.</p>,
        },
      ],
    },
    {
      title: 'Article V: Welfare & Benefits',
      articles: [
        {
          title: 'Section 1: Marital Welfare',
          content: <p>Upon formal marriage, a member in good financial standing (no active outstanding dues) shall receive a cultural token and financial welfare presentation from the Age Grade treasury.</p>,
        },
        {
          title: 'Section 2: Bereavement Support',
          content: <p>In the event of the loss of a member's direct dependent (spouse, parent, or biological child), the Age Grade will provide condolence visits and welfare support. Members are mandated to attend the funeral rites.</p>,
        },
      ],
    },
  ];

  // Filtering based on search
  const filteredSections = sections
    .map((section) => {
      const filteredArticles = section.articles.filter(
        (article) =>
          article.title.toLowerCase().includes(searchTerm.toLowerCase()) ||
          (typeof article.content === 'string' &&
            article.content.toLowerCase().includes(searchTerm.toLowerCase()))
      );
      return { ...section, articles: filteredArticles };
    })
    .filter((section) => section.articles.length > 0);

  return (
    <div className="max-w-3xl mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between bg-card p-6 rounded-xl border border-border shadow-sm">
        <div>
          <h1 className="text-3xl font-extrabold text-primary">Age Grade Constitution</h1>
          <p className="text-muted-foreground text-sm mt-1">OhaBuEnyi Age Grade (Okwojo Ngwo)</p>
        </div>
        <Link
          href="/"
          className="text-sm font-semibold text-primary bg-primary/10 border border-primary/20 px-4 py-2 rounded-lg hover:bg-primary/20 transition cursor-pointer"
        >
          Back Home
        </Link>
      </div>

      {/* Search Filter */}
      <div className="relative">
        <input
          type="text"
          placeholder="Search constitution articles..."
          value={searchTerm}
          onChange={(e) => setSearchTerm(e.target.value)}
          className="w-full px-4 py-3 pl-11 border border-input bg-card text-foreground rounded-xl shadow-sm focus:ring-2 focus:ring-primary focus:border-primary text-sm"
        />
        <span className="absolute left-4 top-3.5 text-muted-foreground">🔍</span>
      </div>

      {/* Document View */}
      <div className="space-y-4">
        {filteredSections.map((section, sIdx) => {
          const isOpen = expandedSection === sIdx;
          return (
            <div key={sIdx} className="bg-card rounded-xl border border-border shadow-sm overflow-hidden">
              <button
                onClick={() => toggleSection(sIdx)}
                className="w-full px-6 py-4 flex justify-between items-center bg-muted/20 hover:bg-muted/40 transition-colors font-bold text-lg text-foreground text-left cursor-pointer"
              >
                <span>{section.title}</span>
                <span className="text-primary text-lg transition-transform duration-200">
                  {isOpen ? '▲' : '▼'}
                </span>
              </button>

              {isOpen && (
                <div className="px-6 py-4 divide-y divide-border/60 space-y-4 bg-card">
                  {section.articles.map((art, aIdx) => (
                    <div key={aIdx} className={`pt-3 ${aIdx === 0 ? 'pt-0' : ''}`}>
                      <h4 className="font-bold text-primary mb-2 text-sm uppercase tracking-wider">{art.title}</h4>
                      <div className="text-foreground/90 text-sm leading-relaxed">{art.content}</div>
                    </div>
                  ))}
                </div>
              )}
            </div>
          );
        })}

        {filteredSections.length === 0 && (
          <div className="text-center p-8 bg-card rounded-xl border border-border text-muted-foreground">
            No constitutional articles match your search query.
          </div>
        )}
      </div>
    </div>
  );
}
